<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>R5a</name>
  <version>0.0.0</version>
  <description>URDF description and mesh assets for the ARX R5A.</description>
  <maintainer email="wee733@users.noreply.github.com">wee733</maintainer>
  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/wee733/Isaac_Ros_CuMotion_ArxR5a</url>
  <url type="bugtracker">https://github.com/wee733/Isaac_Ros_CuMotion_ArxR5a/issues</url>
  <url type="repository">https://github.com/wee733/Isaac_Ros_CuMotion_ArxR5a</url>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  
  <depend>urdf</depend>
  <build_depend>launch_ros</build_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
