<?xml version="1.0"?>
<package format="3">
  <name>arx5_ros2_control</name>
  <version>0.0.1</version>
  <description>ros2_control SystemInterface for ARX5 (joint1..joint8 -> RobotCmd)</description>

  <maintainer email="you@example.com">you</maintainer>
  <license>BSD-3-Clause</license>

  <!-- 关键：用 ament_cmake，而不是 catkin -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>hardware_interface</depend>
  <depend>controller_interface</depend>
  <depend>arx5_arm_msg</depend>

  <export>
    <!-- 让 pluginlib 能在 ament 索引里找到插件描述 -->
    <build_type>ament_cmake</build_type>
    <hardware_interface plugin="${prefix}/share/arx5_ros2_control/plugin.xml"/>
  </export>
</package>

