<?xml version="1.0"?>
<package format="3">
  <name>arx5_ros2_control</name>
  <version>0.0.1</version>
  <description>ros2_control SystemInterface for the ARX R5A driver topics.</description>

  <maintainer email="wee733@users.noreply.github.com">wee733</maintainer>
  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/wee733/Isaac_Ros_CuMotion_ArxR5a</url>
  <url type="bugtracker">https://github.com/wee733/Isaac_Ros_CuMotion_ArxR5a/issues</url>
  <url type="repository">https://github.com/wee733/Isaac_Ros_CuMotion_ArxR5a</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>hardware_interface</depend>
  <depend>controller_interface</depend>
  <depend>arx5_arm_msg</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <hardware_interface plugin="${prefix}/share/arx5_ros2_control/plugin.xml"/>
  </export>
</package>
